name: create PR

on:
  push:

jobs:
  update-input:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Modify input.txt
        run: |
          echo "$(date)" >> input.txt

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
          commit-message: "Update input.txt"
          title: "Update input.txt"
          body: "Updates input.txt"
          branch: "update-input"
          base: v1
          delete-branch: true