name: build image

on:
  push:
    branches:
      - main
jobs:
  get-latest-tag:
    uses: ./.github/workflows/get_latest_tag.yml

  tag_release:
    name: tag version
    needs: get-latest-tag
    outputs:
      part: ${{ steps.bump_tag.outputs.part }}
      tag: ${{ steps.bump_tag.outputs.tag }}
      new_tag: ${{ steps.bump_tag.outputs.new_tag }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        id: bump_tag
        uses: anothrNick/github-tag-action@1.71.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
          TAG_CONTEXT: branch
          RELEASE_BRANCHES: main
          DRY_RUN: true
#          INITIAL_VERSION: ${{ needs.get-latest-tag.outputs.latest_tag }}

      - name: print
        run: |
          echo "latest_tag: ${{ needs.get-latest-tag.outputs.latest_tag }}"
          echo "part: ${{ steps.bump_tag.outputs.part }}"
          echo "tag: ${{ steps.bump_tag.outputs.tag }}"
          echo "new_tag: ${{ steps.bump_tag.outputs.new_tag }}"
