name: build image

on:
  push:
    branches:
      - main
      - v1
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Repository Name
        id: repo_name
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "repo_name=$REPO_NAME" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine latest tags
        id: latest_tags
        run: |
          # Get the latest v1.x.x tag
          LATEST_V1=$(git tag -l "v1.*" | sort -V | tail -n 1)
          if [ -z "$LATEST_V1" ]; then
            LATEST_V1="v1.0.0"
          fi
          echo "latest_v1=$LATEST_V1" >> $GITHUB_ENV
          
          # Get the latest v2.x.x tag
          LATEST_V2=$(git tag -l "v2.*" | sort -V | tail -n 1)
          if [ -z "$LATEST_V2" ]; then
            LATEST_V2="v2.0.0"
          fi
          echo "latest_v2=$LATEST_V2" >> $GITHUB_ENV

      - name: Generate new tag for main branch
        if: github.ref == 'refs/heads/main'
        id: tag_main
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          WITH_V: true
          INITIAL_VERSION: ${{ env.latest_v2 }}
          MAJOR_VERSION_TAG: v2

      - name: Generate new tag for v1 branch
        if: github.ref == 'refs/heads/v1'
        id: tag_v1
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          WITH_V: true
          INITIAL_VERSION: ${{ env.latest_v1 }}
          MAJOR_VERSION_TAG: v1

      - name: Set output tag
        id: set_tag
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "tag=${{ steps.tag_main.outputs.new_tag }}" >> $GITHUB_ENV
          else
            echo "tag=${{ steps.tag_v1.outputs.new_tag }}" >> $GITHUB_ENV
          fi

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          no-cache: 'true'
          tags: |
            ghcr.io/${{ env.repo_name }}:${{ env.tag }}
          labels: |
            org.opencontainers.image.created=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
            org.opencontainers.image.revision=${{ github.sha }}

      - name: run the image
        run: docker run ghcr.io/${{ env.repo_name }}:${{ env.tag }}