name: build image

on:
  push:
    branches:
      - v1
jobs:
  tags:
    name: show_tags
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Tags for Repository Context
        run: |
          echo "Fetching tags for repository..."
          git_refs=$(git for-each-ref --sort=-v:refname --format '%(refname:lstrip=2)')
          echo "Git Refs:"
          echo "$git_refs"
          tagFmt="^v?[0-9]+\.[0-9]+\.[0-9]+$"
          matching_tag_refs=$( (grep -E "$tagFmt" <<< "$git_refs") || true)
          echo "Matching Tag Refs:"
          echo "$matching_tag_refs"
          tag=$(head -n 1 <<< "$matching_tag_refs")
          echo "Latest Tag: $tag"

      - name: Get Tags for Branch Context
        run: |
          echo "Fetching tags for merged branches..."
          git_refs=$(git tag --list --merged HEAD --sort=-committerdate)
          echo "Git Tags:"
          echo "$git_refs"
          
          tagFmt="^v?[0-9]+\.[0-9]+\.[0-9]+$"
          matching_tag_refs=$( (grep -E "$tagFmt" <<< "$git_refs") || true)
          echo "Matching Tag Refs:"
          echo "$matching_tag_refs"
          tag=$(head -n 1 <<< "$matching_tag_refs")
          echo "Latest Tag: $tag"

  tag_release:
    name: tag version
    outputs:
      part: ${{ steps.bump_tag.outputs.part }}
      tag: ${{ steps.bump_tag.outputs.tag }}
      new_tag: ${{ steps.bump_tag.outputs.new_tag }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
          ref: v1
      - name: Bump version and push tag
        id: bump_tag
        uses: anothrNick/github-tag-action@1.71.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
          RELEASE_BRANCHES: v1
          INITIAL_VERSION: 1.0.0
          TAG_CONTEXT: branch
#          DRY_RUN: true

      - name: print
        run: |
          echo "part: ${{ steps.bump_tag.outputs.part }}"
          echo "tag: ${{ steps.bump_tag.outputs.tag }}"
          echo "new_tag: ${{ steps.bump_tag.outputs.new_tag }}"
