name: build image

on:
  push:
    branches:
      - v1
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine new tags
        id: new_tags
        run: |
          # Get the latest v1.x.x tag
          LATEST_V1=$(git tag -l "v1.*" | sort -V | tail -n 1)
          echo "$LATEST_V1"
          if [ -z "$LATEST_V1" ]; then
            LATEST_V1="v1.0.0"
          fi
          IFS='.' read -r major minor patch <<< "$LATEST_V1"
          NEW_V1="$major.$minor.$((patch + 1))"
          echo "new_v1=$NEW_V1" >> $GITHUB_ENV

      - name: Generate new tag for v1 branch
        id: tag_v1
        uses: anothrNick/github-tag-action@1.71.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_TAG: ${{ env.new_v1 }}

      - name: Set output tag
        id: set_tag
        run: |
          echo "tag=${{ steps.tag_v1.outputs.new_tag }}"
