name: Get Latest Tag

on:
  workflow_call:
    inputs:
      branch:
        description: 'branch'
        required: false
        default: 'main'
        type: string
    outputs:
      latest_tag:
        description: 'latest tag'
        value: ${{ jobs.get-latest-tag.outputs.latest_tag }}

jobs:
  get-latest-tag:
    runs-on: ubuntu-latest
    outputs:
      latest_tag: ${{ steps.latest-tag.outputs.latest_tag }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get latest tag in a branch
        run: |
          TAGS=$(git tag --merged "${{ inputs.branch || 'main' }}" | grep -E '^v?[0-9]+\.[0-9]+\.[0-9]+$' | sort -V | tail -n1)
          echo "Latest tag: $TAGS"
          TAG_NO_V=$(echo "$TAGS" | sed 's/^v//')
          echo "latest_tag=$TAG_NO_V" >> $GITHUB_OUTPUT

      - name: print
        run:  |
          echo "latest_tag: ${{ steps.latest-tag.outputs.latest_tag  }}"