name: Matrix Example

on:
  push:

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize matrix file
        run: echo '{"include":[]}' > matrix.json

      - name: Add first tuple
        run: |
          jq '.include += [{"component":"foo","bump":"major"}]' matrix.json > matrix.tmp.json
          mv matrix.tmp.json matrix.json

      - name: Add second tuple
        run: |
          jq '.include += [{"component":"bar","bump":"minor"}]' matrix.json > matrix.tmp.json
          mv matrix.tmp.json matrix.json

      - name: Set matrix output
        id: set-matrix
        run: |
          MATRIX=$(jq -c . matrix.json)  # Compact JSON
          echo "matrix=$MATRIX" >> "$GITHUB_OUTPUT"

  run-matrix:
    needs: generate-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.generate-matrix.outputs.matrix) }}
    steps:
      - name: Run for each component-bump pair
        run: echo "Running job for component=${{ matrix.component }}, bump=${{ matrix.bump }}"
