name: Matrix Example

on:
  push:

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate initial matrix
        id: set-matrix
        run: |
          set -eux
          DATA=$(echo '{}' | jq -c '.include = [{"component":"foo","bump":"major"}]')
          echo "matrix=$DATA" >> "$GITHUB_OUTPUT"

      - name: Append new tuple to matrix
        id: update-matrix
        run: |
          set -eux
          NEW_DATA=$(echo '${{ steps.set-matrix.outputs.matrix }}' | jq -c '.include += [{"component":"bar","bump":"minor"}]')
          echo "matrix=$NEW_DATA" >> "$GITHUB_OUTPUT"

  run-matrix:
    needs: generate-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.generate-matrix.outputs.matrix) }}
    steps:
      - name: Run for each component-bump pair
        run: echo "Running job for component=${{ matrix.component }}, bump=${{ matrix.bump }}"
