name: Write on Push

on:
  push:

jobs:
  write-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Create result file
        run: echo "Hi" > result.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: shared-result
          path: result.txt
